;; PML Standard Library — range.pml
;; Range enhancements (single-argument overload)
;;
;; Usage: (import "range.pml" as range)
;;        (range/range 5)        → (0 1 2 3 4)
;;        (range/range 0 5)      → (0 1 2 3 4)
;;        (range/range 0 10 2)   → (0 2 4 6 8)

;; Full range implementation supporting 1, 2, or 3 arguments.
;; 1 arg:  (range n)        → (0 1 2 ... n-1)
;; 2 args: (range start end) → (start start+1 ... end-1)
;; 3 args: (range start end step) → (start start+step ... up to end-1)
(define (range . args)
  (let ((len (length args)))
    (cond ((= len 1)
           ;; 1 arg: (range end) → (range 0 end 1)
           (let ((_end (car args)))
             (if (>= _end 0)
                 (letrec ((gen (lambda (i acc)
                                 (if (>= i _end)
                                     (reverse acc)
                                     (gen (+ i 1) (cons i acc))))))
                   (gen 0 '()))
                 (error "range: end must be non-negative"))))
          ((= len 2)
           ;; 2 args: (range start end)
           (let ((_start (car args))
                 (_end (cadr args)))
             (letrec ((gen (lambda (i acc)
                             (if (>= i _end)
                                 (reverse acc)
                                 (gen (+ i 1) (cons i acc))))))
               (gen _start '()))))
          ((= len 3)
           ;; 3 args: (range start end step)
           (let ((_start (car args))
                 (_end (cadr args))
                 (_step (caddr args)))
             (if (= _step 0)
                 (error "range: step cannot be zero")
                 (letrec ((gen (lambda (i acc)
                                 (if (if (> _step 0) (>= i _end) (<= i _end))
                                     (reverse acc)
                                     (gen (+ i _step) (cons i acc))))))
                   (gen _start '())))))
          (else
           (error "range: expected 1-3 arguments")))))

(provide range)
