; Example 7: A simple game scene composed from bitmap layers.
; Assets are generated by examples/assets/gen.pml.

(set-backend! "skia")

(define comp (make-composition "scene" 512 512 :bg "#87CEEB"))

; Background grass tile scaled to cover the canvas
(define bg (bitmap-layer "../assets/grass.png"
                         :name "background"
                         :x 0 :y 0
                         :width 512 :height 512))

; A tree and some props
(define tree1 (bitmap-layer "../assets/tree.png"
                            :name "tree-left"
                            :x 60 :y 80
                            :width 128 :height 128))

(define tree2 (bitmap-layer "../assets/tree.png"
                            :name "tree-right"
                            :x 360 :y 100
                            :width 96 :height 96))

; Collectible coins
(define coin1 (bitmap-layer "../assets/coin.png"
                            :name "coin-1"
                            :x 150 :y 320
                            :width 32 :height 32))

(define coin2 (bitmap-layer "../assets/coin.png"
                            :name "coin-2"
                            :x 300 :y 280
                            :width 32 :height 32))

; Player character on top
(define hero (bitmap-layer "../assets/character.png"
                           :name "hero"
                           :x 220 :y 240
                           :width 128 :height 128))

(set! comp (composition-add comp bg tree1 tree2 coin1 coin2 hero))
(composition-render comp "07_bitmap_layer_scene.png")
