#!/usr/bin/env python3
"""
embed_stdlib.py — Embed PML stdlib .pml files as C++ byte arrays.

Usage:
    python tools/embed_stdlib.py <stdlib_dir> <output_header>

Reads all .pml files recursively from <stdlib_dir>, generates a C++23 header
with constexpr byte arrays + lookup table at <output_header>.

The generated header provides:
    - constexpr char stdlib_<path_sanitized>[N] for each file
    - StdlibEntry { path, data, size } entries[] table
    - find_stdlib(path) -> const StdlibEntry* lookup function
"""

import argparse
import os
import sys
from pathlib import Path


def sanitize_path(path: str) -> str:
    """Convert a relative path to a valid C identifier."""
    return path.replace("/", "_").replace(".", "_").replace("-", "_")


def generate_header(stdlib_dir: Path, output_path: Path) -> None:
    """Read all .pml files and generate the C++ header."""

    # Collect all .pml files recursively, sorted for determinism
    pml_files: list[Path] = sorted(stdlib_dir.rglob("*.pml"))

    if not pml_files:
        print(f"Error: No .pml files found in {stdlib_dir}", file=sys.stderr)
        sys.exit(1)

    lines: list[str] = []
    lines.append("// Auto-generated by tools/embed_stdlib.py")
    lines.append(f"// Generated on: {__import__('datetime').datetime.now().strftime('%Y-%m-%d')}")
    lines.append(f"// Source: {len(pml_files)} .pml files from stdlib/")
    lines.append("#pragma once")
    lines.append("")
    lines.append("#include <cstddef>")
    lines.append("#include <cstring>")
    lines.append("")

    entries: list[tuple[str, str, int]] = []

    for pml_file in pml_files:
        rel_path = pml_file.relative_to(stdlib_dir).as_posix()
        sanitized = sanitize_path(rel_path)
        data = pml_file.read_bytes()
        size = len(data)
        var_name = f"stdlib_{sanitized}"

        # Write the byte array (using hex escapes like xxd -i)
        lines.append(f"// {rel_path} ({size} bytes)")
        hex_bytes = data.hex()
        # Split into lines of ~40 hex bytes each
        hex_lines = []
        for i in range(0, len(hex_bytes), 80):
            chunk = hex_bytes[i : i + 80]
            hex_lines.append(
                '"' + "".join(f"\\x{chunk[j:j+2]}" for j in range(0, len(chunk), 2)) + '"'
            )
        array_body = "\n    ".join(hex_lines)
        lines.append(f"constexpr const char {var_name}[{size + 1}] = {array_body};")
        lines.append("")
        entries.append((rel_path, var_name, size))

    # Write the StdlibEntry struct and entries table
    lines.append("struct StdlibEntry {")
    lines.append("  const char* path;   ///< Relative path from stdlib/ (e.g. \"math.pml\")")
    lines.append("  const char* data;   ///< Null-terminated file content")
    lines.append("  size_t size;        ///< File size in bytes (excluding null terminator)")
    lines.append("};")
    lines.append("")

    lines.append("constexpr StdlibEntry stdlib_entries[] = {")
    for rel_path, var_name, size in entries:
        lines.append(f'  {{"{rel_path}", {var_name}, {size}}},')
    lines.append("};")
    lines.append(
        f"constexpr size_t stdlib_entries_count = {len(entries)};"
    )
    lines.append("")

    lines.append("/**")
    lines.append(" * @brief Look up an embedded stdlib file by its relative path.")
    lines.append(" *")
    lines.append(' * @param path Relative path from stdlib/ (e.g. "math.pml", "sprites/body.pml")')
    lines.append(" * @return Pointer to the matching StdlibEntry, or nullptr if not found.")
    lines.append(" */")
    lines.append("inline const StdlibEntry* find_stdlib(const char* path) {")
    lines.append("  for (size_t i = 0; i < stdlib_entries_count; ++i) {")
    lines.append("    if (std::strcmp(stdlib_entries[i].path, path) == 0) {")
    lines.append("      return &stdlib_entries[i];")
    lines.append("    }")
    lines.append("  }")
    lines.append("  return nullptr;")
    lines.append("}")

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines) + "\n")
    print(f"Generated {output_path} ({len(entries)} files, {sum(s for _, _, s in entries)} bytes)")


def main() -> None:
    parser = argparse.ArgumentParser(description="Embed stdlib .pml files as C++ byte arrays")
    parser.add_argument(
        "stdlib_dir",
        type=str,
        default="stdlib",
        nargs="?",
        help="Path to stdlib directory (default: stdlib)",
    )
    parser.add_argument(
        "output_header",
        type=str,
        default="src/pml/core/embedded_stdlib.h",
        nargs="?",
        help="Output header path (default: src/pml/core/embedded_stdlib.h)",
    )
    args = parser.parse_args()

    stdlib_dir = Path(args.stdlib_dir)
    if not stdlib_dir.is_dir():
        print(f"Error: stdlib directory not found: {stdlib_dir}", file=sys.stderr)
        sys.exit(1)

    output_path = Path(args.output_header)
    generate_header(stdlib_dir, output_path)


if __name__ == "__main__":
    main()
