#!/usr/bin/env python3
"""
embed_stdlib.py — Embeds all .pml standard library files as C++ byte arrays.

Reads all .pml files from stdlib/ recursively, generates embedded_stdlib.h
with constexpr byte arrays, a lookup table, and a find_stdlib() function.

Usage: python tools/embed_stdlib.py
Output: pml-cpp/src/pml/core/embedded_stdlib.h
"""

import os
import re
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
STDLIB_DIR = PROJECT_ROOT / "stdlib"
OUTPUT_DIR = PROJECT_ROOT / "pml-cpp" / "src" / "pml" / "core"
OUTPUT_FILE = OUTPUT_DIR / "embedded_stdlib.h"


def path_to_ident(path: str) -> str:
    """Convert a file path like stdlib/sprites/body.pml to a valid C identifier.

    Rules:
        - Replace non-alphanumeric chars with underscore
        - Collapse multiple underscores
        - Strip leading/trailing underscores
    """
    # Strip .pml extension, replace separators and dots with underscore
    ident = re.sub(r'[^a-zA-Z0-9]', '_', path)
    # Collapse multiple underscores
    ident = re.sub(r'_+', '_', ident)
    # Strip leading/trailing underscores
    ident = ident.strip('_')
    # Ensure it starts with a letter or underscore
    if ident and ident[0].isdigit():
        ident = '_' + ident
    if not ident:
        ident = 'stdlib_file'
    return ident


def make_byte_array(data: bytes) -> str:
    """Convert bytes to xxd-style C string literal (hex escapes).

    Generates a single-line string literal with \\xHH escapes for each byte.
    Splits into multiple literals if the line would be unreasonably long.
    """
    if not data:
        return '""'

    # Build hex escape sequence
    escaped = ''.join(f'\\x{b:02x}' for b in data)
    return f'"{escaped}"'


def generate_header(file_entries: list[tuple[str, str, bytes]]) -> str:
    """Generate the complete header file content.

    Args:
        file_entries: List of (relative_path, identifier, content_bytes) tuples,
                      sorted by path.
    """
    lines: list[str] = []
    lines.append('// Auto-generated by tools/embed_stdlib.py')
    lines.append(f'// Generated on: 2026-06-16')
    lines.append(f'// Source: {len(file_entries)} .pml files from stdlib/')
    lines.append('#pragma once')
    lines.append('')
    lines.append('#include <cstddef>')
    lines.append('#include <cstring>')
    lines.append('')

    # --- byte arrays ---
    for rel_path, ident, content in file_entries:
        escaped = make_byte_array(content)
        n_bytes = len(content)
        lines.append(f'// {rel_path} ({n_bytes} bytes)')
        lines.append(f'constexpr const char stdlib_{ident}[{n_bytes + 1}] = {escaped};')
        lines.append('')

    # --- StdlibEntry struct ---
    lines.append('struct StdlibEntry {')
    lines.append('  const char* path;   ///< Relative path from stdlib/ (e.g. "math.pml")')
    lines.append('  const char* data;   ///< Null-terminated file content')
    lines.append('  size_t size;        ///< File size in bytes (excluding null terminator)')
    lines.append('};')
    lines.append('')

    # --- entries array ---
    lines.append('constexpr StdlibEntry stdlib_entries[] = {')
    for rel_path, ident, content in file_entries:
        lines.append(f'  {{"{rel_path}", stdlib_{ident}, {len(content)}}},')
    lines.append('};')
    lines.append(f'constexpr size_t stdlib_entries_count = {len(file_entries)};')
    lines.append('')

    # --- find function ---
    lines.append('/**')
    lines.append(' * @brief Look up an embedded stdlib file by its relative path.')
    lines.append(' *')
    lines.append(' * @param path Relative path from stdlib/ (e.g. "math.pml", "sprites/body.pml")')
    lines.append(' * @return Pointer to the matching StdlibEntry, or nullptr if not found.')
    lines.append(' */')
    lines.append('inline const StdlibEntry* find_stdlib(const char* path) {')
    lines.append('  for (size_t i = 0; i < stdlib_entries_count; ++i) {')
    lines.append('    if (std::strcmp(stdlib_entries[i].path, path) == 0) {')
    lines.append('      return &stdlib_entries[i];')
    lines.append('    }')
    lines.append('  }')
    lines.append('  return nullptr;')
    lines.append('}')
    lines.append('')

    return '\n'.join(lines)


def main() -> None:
    # Find all .pml files recursively
    if not STDLIB_DIR.is_dir():
        print(f"Error: stdlib directory not found: {STDLIB_DIR}", file=sys.stderr)
        sys.exit(1)

    pml_files = sorted(STDLIB_DIR.rglob("*.pml"))

    if not pml_files:
        print(f"Error: no .pml files found in {STDLIB_DIR}", file=sys.stderr)
        sys.exit(1)

    entries: list[tuple[str, str, bytes]] = []
    for fpath in pml_files:
        rel_path = str(fpath.relative_to(STDLIB_DIR))
        content = fpath.read_bytes()
        ident = path_to_ident(rel_path)
        entries.append((rel_path, ident, content))

    # Generate header
    header = generate_header(entries)

    # Write output
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    OUTPUT_FILE.write_text(header)

    total_bytes = sum(len(c) for _, _, c in entries)
    print(f"✓ Generated {OUTPUT_FILE}")
    print(f"  {len(entries)} files, {total_bytes} bytes embedded")
    for rel_path, _, content in entries:
        print(f"    {rel_path:40s} {len(content):6d} B")


if __name__ == "__main__":
    main()
