#pragma once

// ==========================================================================================================================================================================================================================================═
// PML Embedded Stdlib Loader
// ------------------------------------------------------------------------------------------------------------------------------------------------------------─
// Loads embedded standard library .pml modules (generated by
// tools/embed_stdlib.py) into the global environment.
//
// The embedded data lives in src/pml/core/embedded_stdlib.h (auto-generated,
// DO NOT MODIFY). This header provides the function to load all those
// modules at runtime.
// ==========================================================================================================================================================================================================================================═

#include <memory>

namespace pml {

class Environment;

/// Load all embedded standard library modules into `global_env`.
///
/// Iterates `stdlib_entries[]` from the auto-generated embedded_stdlib.h,
/// lexes, parses, expands macros, and evaluates each .pml module's content
/// directly into the provided environment. On per-module failure, a warning
/// is printed to stderr and loading continues with the next module.
///
/// @param global_env  The root/global environment to install stdlib bindings into.
void load_embedded_stdlib(std::shared_ptr<Environment> global_env);

}  // namespace pml
